name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        php: ['7.4', '8.0']
        dependency-version: [prefer-stable]

    name: PHP ${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      
   -  name: Phpinsights
   - uses: MilesChou/composer-action@master

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: fileinfo
        tools: composer:v2
        coverage: pcov

    - name: Setup Problem Matches
      run: |
        echo "::add-matcher::${{ runner.tool_cache }}/php.json"
        echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
    - name: Install Composer dependencies
      run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist --no-suggest

    - name: PHPUnit Testing
      run: vendor/bin/pest --coverage

	- name: Phpinsights Testing
	- run: vendor/bin/phpinsights -n --ansi --format=github-action

    - name: Build
      run: php webzone app:build --build-version=0.0

    - name: Build Check
      run: php builds/webzone --version